// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';
import {user} from '../models';

export function GetSessions():Promise<Array<desktop.Entry>>;

export function GetUserAvatar(arg1:string):Promise<string>;

export function GetUsers():Promise<Array<user.User>>;

export function Login(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ReadConfig():Promise<any>;

export function SaveConfig(arg1:any):Promise<void>;
