// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetUserAvatar(arg1) {
  return window['go']['main']['App']['GetUserAvatar'](arg1);
}

export function GetUsers() {
  return window['go']['main']['App']['GetUsers']();
}

export function Login(arg1, arg2, arg3) {
  return window['go']['main']['App']['Login'](arg1, arg2, arg3);
}

export function ReadConfig() {
  return window['go']['main']['App']['ReadConfig']();
}

export function Reboot() {
  return window['go']['main']['App']['Reboot']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function Shutdown() {
  return window['go']['main']['App']['Shutdown']();
}
